name: Test Node.js App

on:
  push:
    branches:
      - docker-push

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ github.sha | slice(0, 5) }}

    - name: Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ github.sha | slice(0, 5) }}